# Generated by Django 3.2.19 on 2023-05-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='status_friendship',
            field=models.CharField(choices=[('NR', 'Заявка не отправлена'), ('OU', 'Исходящая заявка'), ('IN', 'Входящая заявка'), ('PE', 'Ожидается ответ'), ('RE', 'Заявка отклонена'), ('AC', 'Заявка принята')], default='NR', max_length=2),
        ),
    ]
